apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: next-prod

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: patch-deployment.yaml

images:
  - name: next-app
    newName: ghcr.io/knougitrepos/next
    newTag: master-0bfde1b-20260102122827
