apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: next-prod

resources:
  - ../../base
  - namespace.yaml
  - secret.yaml

patches:
  - path: patch-deployment.yaml

images:
  - name: next-app
    newName: ghcr.io/knougitrepos/next
    newTag: master-b4609c9-20260118133219
